"""initial schema

Revision ID: 6c64e230860d
Revises: 
Create Date: 2026-10-02 10:13:58.669827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c64e230860d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('prenom', sa.String(length=200), nullable=False),
    sa.Column('nom_norm', sa.String(length=200), nullable=False),
    sa.Column('prenom_norm', sa.String(length=200), nullable=False),
    sa.Column('sexe', sa.String(length=10), nullable=True),
    sa.Column('merged_into_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merged_into_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_persons_names_norm', 'persons', ['nom_norm', 'prenom_norm'], unique=False)
    op.create_table('source_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('formation_id', sa.Integer(), nullable=True),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('date_inscription', sa.Date(), nullable=True),
    sa.Column('nom_submitted', sa.String(length=200), nullable=True),
    sa.Column('prenom_submitted', sa.String(length=200), nullable=True),
    sa.Column('email_submitted', sa.String(length=320), nullable=True),
    sa.Column('phone_submitted', sa.String(length=50), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['formation_id'], ['formations.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registrations_formation_id'), 'registrations', ['formation_id'], unique=False)
    op.create_index(op.f('ix_registrations_person_id'), 'registrations', ['person_id'], unique=False)
    op.create_index(op.f('ix_registrations_source_file_id'), 'registrations', ['source_file_id'], unique=False)
    op.create_table('match_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=True),
    sa.Column('person_a_id', sa.Integer(), nullable=False),
    sa.Column('person_b_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conflicts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['person_a_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['person_b_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_results_person_a_id'), 'match_results', ['person_a_id'], unique=False)
    op.create_index(op.f('ix_match_results_person_b_id'), 'match_results', ['person_b_id'], unique=False)
    op.create_index(op.f('ix_match_results_status'), 'match_results', ['status'], unique=False)
    op.create_table('person_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('first_seen_registration_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['first_seen_registration_id'], ['registrations.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'email')
    )
    op.create_index(op.f('ix_person_emails_email'), 'person_emails', ['email'], unique=False)
    op.create_index(op.f('ix_person_emails_person_id'), 'person_emails', ['person_id'], unique=False)
    op.create_table('person_phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('first_seen_registration_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['first_seen_registration_id'], ['registrations.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'phone')
    )
    op.create_index(op.f('ix_person_phones_person_id'), 'person_phones', ['person_id'], unique=False)
    op.create_index(op.f('ix_person_phones_phone'), 'person_phones', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_person_phones_phone'), table_name='person_phones')
    op.drop_index(op.f('ix_person_phones_person_id'), table_name='person_phones')
    op.drop_table('person_phones')
    op.drop_index(op.f('ix_person_emails_person_id'), table_name='person_emails')
    op.drop_index(op.f('ix_person_emails_email'), table_name='person_emails')
    op.drop_table('person_emails')
    op.drop_index(op.f('ix_match_results_status'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_person_b_id'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_person_a_id'), table_name='match_results')
    op.drop_table('match_results')
    op.drop_index(op.f('ix_registrations_source_file_id'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_person_id'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_formation_id'), table_name='registrations')
    op.drop_table('registrations')
    op.drop_table('source_files')
    op.drop_index('ix_persons_names_norm', table_name='persons')
    op.drop_table('persons')
    op.drop_table('formations')
    # ### end Alembic commands ###
