"""trigram name indexes

Revision ID: 99e6b4137e70
Revises: eb814bb6011f
Create Date: 2026-10-02 11:45:26.067542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99e6b4137e70'
down_revision: Union[str, Sequence[str], None] = 'eb814bb6011f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_persons_nom_trgm', 'persons', ['nom_norm'], unique=False, postgresql_using='gin', postgresql_ops={'nom_norm': 'gin_trgm_ops'})
    op.create_index('ix_persons_prenom_trgm', 'persons', ['prenom_norm'], unique=False, postgresql_using='gin', postgresql_ops={'prenom_norm': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_persons_prenom_trgm', table_name='persons', postgresql_using='gin', postgresql_ops={'prenom_norm': 'gin_trgm_ops'})
    op.drop_index('ix_persons_nom_trgm', table_name='persons', postgresql_using='gin', postgresql_ops={'nom_norm': 'gin_trgm_ops'})
    # ### end Alembic commands ###
