"""person merges

Revision ID: c1765979de36
Revises: 8826878784a4
Create Date: 2026-10-05 08:35:22.365849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1765979de36'
down_revision: Union[str, Sequence[str], None] = '8826878784a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_merges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_person_id', sa.Integer(), nullable=False),
    sa.Column('target_person_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('performed_by', sa.String(length=100), nullable=True),
    sa.Column('undone_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('undone_by', sa.String(length=100), nullable=True),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['match_results.id'], ),
    sa.ForeignKeyConstraint(['source_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['target_person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_merges_source_person_id'), 'person_merges', ['source_person_id'], unique=False)
    op.create_index(op.f('ix_person_merges_target_person_id'), 'person_merges', ['target_person_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_person_merges_target_person_id'), table_name='person_merges')
    op.drop_index(op.f('ix_person_merges_source_person_id'), table_name='person_merges')
    op.drop_table('person_merges')
    # ### end Alembic commands ###
