"""import log

Revision ID: d8c14beb3a1b
Revises: c1765979de36
Create Date: 2026-10-05 10:39:29.908435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8c14beb3a1b'
down_revision: Union[str, Sequence[str], None] = 'c1765979de36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('field', sa.String(length=50), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('original', sa.Text(), nullable=True),
    sa.Column('normalized', sa.Text(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_log_source_file_id'), 'import_log', ['source_file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_log_source_file_id'), table_name='import_log')
    op.drop_table('import_log')
    # ### end Alembic commands ###
