"""source file hash

Revision ID: eb814bb6011f
Revises: 6c64e230860d
Create Date: 2026-10-02 10:59:00.889684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb814bb6011f'
down_revision: Union[str, Sequence[str], None] = '6c64e230860d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_files', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_source_files_file_hash'), 'source_files', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_files_file_hash'), table_name='source_files')
    op.drop_column('source_files', 'file_hash')
    # ### end Alembic commands ###
